version: '3'
services:
  app:
    container_name: app
    build: .
    working_dir: /src
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - .:/ticket
    restart: always
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=test
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
